library(testit)
library(PKPDsim)
a <- new_regimen(amt = 10, n = 5, interval = 12)
b <- regimen_to_nm(a, t_obs = c(1,2,3))
assert("correct length", length(b[,1]) == 8)
assert("correct width", length(b[1,]) == 7)
