# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pk_1cmt_iv_bolus <- function(d) {
    .Call('_PKPDsim_pk_1cmt_iv_bolus', PACKAGE = 'PKPDsim', d)
}

pk_1cmt_iv_bolus_covariates <- function(data, parameters, covariates, covariate_model) {
    .Call('_PKPDsim_pk_1cmt_iv_bolus_covariates', PACKAGE = 'PKPDsim', data, parameters, covariates, covariate_model)
}

pk_1cmt_iv_infusion <- function(d) {
    .Call('_PKPDsim_pk_1cmt_iv_infusion', PACKAGE = 'PKPDsim', d)
}

pk_1cmt_oral <- function(d) {
    .Call('_PKPDsim_pk_1cmt_oral', PACKAGE = 'PKPDsim', d)
}

pk_2cmt_iv_bolus <- function(d) {
    .Call('_PKPDsim_pk_2cmt_iv_bolus', PACKAGE = 'PKPDsim', d)
}

pk_2cmt_iv_infusion <- function(d) {
    .Call('_PKPDsim_pk_2cmt_iv_infusion', PACKAGE = 'PKPDsim', d)
}

pk_2cmt_oral <- function(d) {
    .Call('_PKPDsim_pk_2cmt_oral', PACKAGE = 'PKPDsim', d)
}

pk_3cmt_iv_bolus <- function(d) {
    .Call('_PKPDsim_pk_3cmt_iv_bolus', PACKAGE = 'PKPDsim', d)
}

pk_3cmt_iv_infusion <- function(d) {
    .Call('_PKPDsim_pk_3cmt_iv_infusion', PACKAGE = 'PKPDsim', d)
}

pk_3cmt_oral <- function(d) {
    .Call('_PKPDsim_pk_3cmt_oral', PACKAGE = 'PKPDsim', d)
}

